import { ThemeConfig } from '../types';

const baseSizes = {
    xs: {
        fontSize: '0.6875rem',
        padding: '0.25rem 0.5rem',
        height: '1.625rem',
        borderRadius: '0.25rem',
    },
    sm: {
        fontSize: '0.75rem',
        padding: '0.3125rem 0.625rem',
        height: '1.875rem',
        borderRadius: '0.25rem',
    },
    md: {
        fontSize: '0.8125rem',
        padding: '0.375rem 0.75rem',
        height: '2.125rem',
        borderRadius: '0.375rem',
    },
    lg: {
        fontSize: '0.875rem',
        padding: '0.4375rem 0.875rem',
        height: '2.375rem',
        borderRadius: '0.375rem',
    },
    xl: {
        fontSize: '0.9375rem',
        padding: '0.5rem 1rem',
        height: '2.625rem',
        borderRadius: '0.5rem',
    },
};

export const themes: Record<string, ThemeConfig> = {
    default: {
        colors: {
            primary: '#3b82f6',
            secondary: '#64748b',
            success: '#10b981',
            danger: '#ef4444',
            warning: '#f59e0b',
            info: '#06b6d4',
            light: '#f8fafc',
            dark: '#1e293b',
            background: '#ffffff',
            surface: '#f8fafc',
            text: '#1e293b',
            textSecondary: '#64748b',
            border: '#e2e8f0',
            focus: '#3b82f6',
            hover: '#f1f5f9',
            disabled: '#f1f5f9',
            placeholder: '#94a3b8',
        },
        sizes: baseSizes,
        borderWidth: '1px',
        borderRadius: '0.5rem',
        fontSize: '1rem',
        fontColor: '#1e293b',
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
        placeholderStyles: {
            fontSize: '1rem',
            color: '#94a3b8',
            fontStyle: 'normal',
        },
    },
    primary: {
        colors: {
            primary: '#2563eb',
            secondary: '#475569',
            success: '#059669',
            danger: '#dc2626',
            warning: '#d97706',
            info: '#0891b2',
            light: '#f1f5f9',
            dark: '#0f172a',
            background: '#ffffff',
            surface: '#f1f5f9',
            text: '#0f172a',
            textSecondary: '#475569',
            border: '#cbd5e1',
            focus: '#2563eb',
            hover: '#e2e8f0',
            disabled: '#e2e8f0',
            placeholder: '#64748b',
        },
        sizes: baseSizes,
        borderWidth: '1px',
        borderRadius: '0.375rem',
        fontSize: '1rem',
        fontColor: '#0f172a',
        backgroundColor: '#ffffff',
        borderColor: '#cbd5e1',
        placeholderStyles: {
            fontSize: '1rem',
            color: '#64748b',
            fontStyle: 'normal',
        },
    },
    secondary: {
        colors: {
            primary: '#64748b',
            secondary: '#94a3b8',
            success: '#22c55e',
            danger: '#f87171',
            warning: '#fbbf24',
            info: '#38bdf8',
            light: '#f8fafc',
            dark: '#334155',
            background: '#ffffff',
            surface: '#f8fafc',
            text: '#334155',
            textSecondary: '#64748b',
            border: '#e2e8f0',
            focus: '#64748b',
            hover: '#f1f5f9',
            disabled: '#f1f5f9',
            placeholder: '#94a3b8',
        },
        sizes: baseSizes,
        borderWidth: '1px',
        borderRadius: '0.75rem',
        fontSize: '1rem',
        fontColor: '#334155',
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
        placeholderStyles: {
            fontSize: '1rem',
            color: '#94a3b8',
            fontStyle: 'normal',
        },
    },
    success: {
        colors: {
            primary: '#10b981',
            secondary: '#6b7280',
            success: '#059669',
            danger: '#dc2626',
            warning: '#d97706',
            info: '#0891b2',
            light: '#f0fdf4',
            dark: '#064e3b',
            background: '#ffffff',
            surface: '#f0fdf4',
            text: '#064e3b',
            textSecondary: '#047857',
            border: '#bbf7d0',
            focus: '#10b981',
            hover: '#dcfce7',
            disabled: '#dcfce7',
            placeholder: '#6b7280',
        },
        sizes: baseSizes,
        borderWidth: '1px',
        borderRadius: '0.5rem',
        fontSize: '1rem',
        fontColor: '#064e3b',
        backgroundColor: '#ffffff',
        borderColor: '#bbf7d0',
        placeholderStyles: {
            fontSize: '1rem',
            color: '#6b7280',
            fontStyle: 'normal',
        },
    },
    dark: {
        colors: {
            primary: '#60a5fa',
            secondary: '#9ca3af',
            success: '#34d399',
            danger: '#f87171',
            warning: '#fbbf24',
            info: '#38bdf8',
            light: '#374151',
            dark: '#f9fafb',
            background: '#1f2937',
            surface: '#374151',
            text: '#f9fafb',
            textSecondary: '#d1d5db',
            border: '#4b5563',
            focus: '#60a5fa',
            hover: '#4b5563',
            disabled: '#4b5563',
            placeholder: '#9ca3af',
        },
        sizes: baseSizes,
        borderWidth: '1px',
        borderRadius: '0.5rem',
        fontSize: '1rem',
        fontColor: '#f9fafb',
        backgroundColor: '#374151',
        borderColor: '#4b5563',
        placeholderStyles: {
            fontSize: '1rem',
            color: '#9ca3af',
            fontStyle: 'normal',
        },
    },
};
