export { default as AngleLeftIcon } from './icons/angle-left.svg?react';
export { default as AngleRightIcon } from './icons/angle-right.svg?react';
export { default as AnnouncementIcon } from './icons/announcement.svg?react';
export { default as ArchivedIcon } from './icons/archived.svg?react';
export { default as ArrowDownIcon } from './icons/arrow-down.svg?react';
export { default as ArrowUpIcon } from './icons/arrow-up.svg?react';
export { default as BackIcon } from './icons/back-arrow.svg?react';
export { default as BarChartIcon } from './icons/bar-chart.svg?react';
export { default as BranchIcon } from './icons/branch.svg?react';
export { default as BrightSunIcon } from './icons/bright-sun.svg?react';
export { default as BrowserCookieIcon } from './icons/browser-cookie.svg?react';
export { default as BuildingIcon } from './icons/building.svg?react';
export { default as CalendarLineIcon } from './icons/calendar-line.svg?react';
export { default as CalendarIcon } from './icons/calendar.svg?react';
export { default as CheckCircleIcon, default as SuccessIcon } from './icons/check-circle.svg?react';
export { default as CheckIcon } from './icons/check.svg?react';
export { default as ChevronDownIcon } from './icons/chevron-down.svg?react';
export { default as ChevronLeftIcon } from './icons/chevron-left.svg?react';
export { default as ChevronRightIcon } from './icons/chevron-right.svg?react';
export { default as ChevronUpIcon } from './icons/chevron-up.svg?react';
export { default as ClockIcon } from './icons/clock.svg?react';
export { default as CopyIcon } from './icons/copy.svg?react';
export { default as DashboardIcon } from './icons/dashboard.svg?react';
export { default as DownloadIcon } from './icons/download.svg?react';
export { default as EditIcon } from './icons/edit.svg?react';
export { default as ErrorIcon } from './icons/error.svg?react';
export { default as ExternalLinkIcon } from './icons/external-link.svg?react';
export { default as EyeSlashIcon } from './icons/eye-slash.svg?react';
export { default as EyeIcon } from './icons/eye.svg?react';
export { default as FilterIcon } from './icons/filter.svg?react';
export { default as HelpIcon } from './icons/help.svg?react';
export { default as InfoIcon } from './icons/info.svg?react';
export { default as LineChartUpIcon } from './icons/line-chart-up.svg?react';
export { default as LoadingIcon } from './icons/loading.svg?react';
export { default as LocationIcon, default as TreeIcon } from './icons/location.svg?react';
export { default as LogoutIcon } from './icons/logout.svg?react';
export { default as MenuIcon } from './icons/menu.svg?react';
export { default as MinusIcon } from './icons/minus.svg?react';
export { default as NightLightIcon } from './icons/night-light.svg?react';
export { default as AuthIcon } from './icons/oAuth.svg?react';
export { default as PasswordIcon } from './icons/password.svg?react';
export { default as PauseIcon } from './icons/pause.svg?react';
export { default as PlayIcon } from './icons/play.svg?react';
export { default as PlusIconThin } from './icons/plus-2.svg?react';
export { default as PlusBoxIcon } from './icons/plus-box.svg?react';
export { default as PlusIconSolid } from './icons/plus-solid.svg?react';
export { default as PlusIcon } from './icons/plus.svg?react';
export { default as PrintIcon } from './icons/print.svg?react';
export { default as QuestionCircle } from './icons/question-circle.svg?react';
export { default as QueueIcon } from './icons/queue.svg?react';
export { default as FlagIcon } from './icons/red-flag.svg?react';
export { default as RefreshIcon } from './icons/refresh.svg?react';
export { default as SearchIcon } from './icons/search.svg?react';
export { default as SettingsIcon } from './icons/settings.svg?react';
export { default as ShareIcon } from './icons/share.svg?react';
export { default as SortIcon } from './icons/sort.svg?react';
export { default as StopIcon } from './icons/stop.svg?react';
export { default as ExcludeIcon, default as TimesCircleIcon } from './icons/times-circle.svg?react';
export { default as TimesIcon } from './icons/times.svg?react';
export { default as ListIcon } from './icons/todo-list.svg?react';
export { default as TrashIcon } from './icons/trash.svg?react';
export { default as UploadIcon } from './icons/upload.svg?react';
export { default as UserGroupIcon } from './icons/user-group.svg?react';
export { default as UserIcon } from './icons/user.svg?react';
export { default as WarningIcon } from './icons/warning.svg?react';
export { default as WebsiteIcon } from './icons/web.svg?react';

/// Items to take care
export { default as ArrowRightIcon } from './icons/web.svg?react';
export { default as AlertIcon } from './icons/web.svg?react';
export { default as FileUpload } from './icons/web.svg?react';
export { default as FolderIcon } from './icons/web.svg?react';
export { default as BadgeIcon } from './icons/web.svg?react';
export { default as AwardIcon } from './icons/web.svg?react';
export { default as SaveIcon } from './icons/web.svg?react';
export { default as SendIcon } from './icons/web.svg?react';
export { default as TrophyIcon } from './icons/web.svg?react';
export { default as PaletteIcon } from './icons/web.svg?react';
export { default as ShieldIcon } from './icons/web.svg?react';
export { default as BlockIcon } from './icons/web.svg?react';
export { default as PieChartIcon } from './icons/web.svg?react';
export { default as UsersIcon } from './icons/web.svg?react';

export type SVGIcon = React.FunctionComponent<
    React.ComponentProps<'svg'> & { title?: string; titleId?: string; desc?: string; descId?: string }
>;
